# secrets:
#   aws_shared_credentials:
#     file: ~/.aws/secrets/aws_shared_credentials.secret
#   aws_hosted_zone_id:
#     file: ~/.aws/secrets/aws_hosted_zone_id.secret

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
      traefik.http.routers.whoami.entrypoints: web
      # traefik.http.routers.whoami.entrypoints: websecure  # HTTPS利用する場合はこちらを有効にする
      # traefik.http.routers.whoami.tls.certresolver: router53 # Route53のDNS-01 Challengeを利用する場合はこちらを有効にする
      traefik.http.routers.whoami.middlewares: auth
      traefik.http.middlewares.auth.basicauth.users: traefik:$$apr1$$O.gNZ5Wi$$METL47gzUCYaBQbtNi7WK1
    restart: always
    networks:
      - app-network

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      # - "443:443/tcp"
    networks:
      - app-network
    environment:
      TZ: Asia/Tokyo
    labels:
      traefik.enable: true
      traefik.http.routers.dashboard.rule: Host(`traefik.localhost`)
      traefik.http.routers.dashboard.entrypoints: web
      traefik.http.routers.dashboard.service: api@internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro

networks:
  app-network:
    external: false
